# Generated by Django 5.2.8 on 2025-11-29 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_subscription_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={"verbose_name": "Подписка", "verbose_name_plural": "Подписки"},
        ),
    ]
