# Generated by Django 5.2.8 on 2025-11-15 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the course title', max_length=200, verbose_name='title')),
                ('preview', models.ImageField(blank=True, help_text='Upload a course preview image', null=True, upload_to='courses/previews/', verbose_name='preview image')),
                ('description', models.TextField(blank=True, help_text='Enter the course description', verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the lesson title', max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, help_text='Enter the lesson description', verbose_name='description')),
                ('preview', models.ImageField(blank=True, help_text='Upload a lesson preview image', null=True, upload_to='lessons/previews/', verbose_name='preview image')),
                ('video_url', models.URLField(blank=True, help_text='Enter the video URL for this lesson', verbose_name='video URL')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lesson order in the course', verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('course', models.ForeignKey(help_text='Select the course for this lesson', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='materials.course', verbose_name='course')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'ordering': ['course', 'order', 'created_at'],
            },
        ),
    ]
