# Generated by Django 5.2.8 on 2025-11-25 18:05

import materials.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Enter the video URL for this lesson",
                validators=[materials.validators.validate_youtube_url],
                verbose_name="video URL",
            ),
        ),
    ]
