# Generated by Django 5.2.8 on 2025-11-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_lesson_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Цена курса"),
        ),
    ]
